export const dataInput = [
  {
    title: 'Login',
    id: 'login',
    name: 'login',
    value: '',
    placeholder: '',
    type: 'text',
  },
  {
    title: 'First name',
    id: 'first_name',
    name: 'first_name',
    value: '',
    placeholder: '',
    type: 'text',
  },
  {
    title: 'Second name',
    id: 'second_name',
    name: 'second_name',
    value: '',
    placeholder: '',
    type: 'text',
  },
  {
    title: 'Display name',
    id: 'display_name',
    name: 'display_name',
    value: '',
    placeholder: '',
    type: 'text',
  },
  {
    title: 'phone',
    id: 'phone',
    name: 'phone',
    value: '',
    placeholder: '',
    type: 'tel',
  },
  {
    title: 'email',
    id: 'email',
    name: 'email',
    value: '',
    placeholder: '',
    type: 'email',
  },
]
